name       : grep
version    : '3.1'
release    : 8
source     :
    - ftp://ftp.gnu.org/gnu/grep/grep-3.1.tar.xz : db625c7ab3bb3ee757b3926a5cfa8d9e1c3991ad24707a83dde8a5ef2bf7a07e
license    : GPL-3.0
component  : system.base
summary    : grep (pattern searching tool)
description: |
    grep stands for global / regular expression / print, and is used to search for patterns and strings within text files.
setup      : |
    %configure --bindir=/bin
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 ${installdir}/usr/bin

    for i in egrep fgrep grep; do
        ln -sv /bin/$i ${installdir}/usr/bin/$i
    done
