name       : grep
version    : '3.4'
release    : 11
source     :
    - https://ftp.gnu.org/gnu/grep/grep-3.4.tar.xz : 58e6751c41a7c25bfc6e9363a41786cff3ba5709cf11d5ad903cf7cce31cc3fb
license    : GPL-3.0-or-later
component  : system.base
summary    : grep (pattern searching tool)
description: |
    grep stands for global / regular expression / print, and is used to search for patterns and strings within text files.
setup      : |
    %configure --bindir=/bin
build      : |
    %make
install    : |
    %make_install
    install -d -m00755 ${installdir}/usr/bin

    for i in egrep fgrep grep; do
        ln -sv /bin/$i ${installdir}/usr/bin/$i
    done
check      : |
    %make check
